function costRow = buildCostRow(specificGeneratorData)
noLoad=specificGeneratorData.cost.noLoad;
PMAX=specificGeneratorData.PMAX;
PMIN=specificGeneratorData.PMIN;
segmentLength=specificGeneratorData.cost.segmentLength;
segmentSlopes=specificGeneratorData.cost.segmentSlopes;
costRow=[1	0	0	4,...
    PMIN                    noLoad,...
    PMIN+segmentLength      noLoad+segmentLength*segmentSlopes(1),...
    PMIN+2*segmentLength    noLoad+segmentLength*(segmentSlopes(1)+segmentSlopes(2)),...
    PMIN+3*segmentLength    noLoad+segmentLength*(segmentSlopes(1)+segmentSlopes(2)+segmentSlopes(3))];
end

%     PMIN-epsilon            0,...
